In [1]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/heart.csv")

In [3]:
df.head(n=10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

In [4]:
df.shape

(303, 14)

#### Statistical measures

In [5]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

#### Check for missing values

In [6]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Distribution of target variable

In [7]:
df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

### Split features and target

In [8]:
X = df.drop(["target"], axis=1)
y = df["target"]

In [9]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

### Split data into training data and testing data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=3)

In [11]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)


## Comparing performance of the models

In [12]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [13]:
def compare_models_train_test():
    """ This is a function to compare the accuracy score of ML models. """
    
    for model in models:
        model.fit(X_train, y_train)  # train model
        test_data_prediction = model.predict(X_test)  # evaluate model
        accuracy = accuracy_score(y_test, test_data_prediction)
        print(f"Accuracy score for {model}: {accuracy}")

compare_models_train_test()

Accuracy score for LogisticRegression(max_iter=1000): 0.7704918032786885
Accuracy score for SVC(kernel='linear'): 0.7704918032786885
Accuracy score for KNeighborsClassifier(): 0.6557377049180327
Accuracy score for RandomForestClassifier(): 0.7868852459016393


## Cross validation

#### 1. Logistic Regression

In [20]:
# Cross validation for Logistic Regression model
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000), X, y, cv=5)

In [15]:
print(cv_score_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]


In [19]:
# mean accuracy score for the Logistic Regression model
# find the mean and convert into a percentage, round off the percentage value to 2 decimal places
mean_accuracy_lr = round(sum(cv_score_lr) / len(cv_score_lr)*100, 2)

print(mean_accuracy_lr)

82.83


#### 2. Support Vector Classifier

In [23]:
# Cross validation for SVM model
cv_score_svc = cross_val_score(SVC(kernel='linear'), X, y, cv=5)

print(cv_score_svc)

# mean accuracy score for the Support Vector Machine (SVM) model
# find the mean and convert into a percentage, round off the percentage value to 2 decimal places
mean_accuracy_svc = round(sum(cv_score_svc) / len(cv_score_svc)*100, 2)

print(mean_accuracy_svc)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83


##### Create a function to compare the models

In [29]:
def models_comparison_using_cross_validation():
    for model in models:
        cv_score = cross_val_score(model, X, y, cv=5)
        mean_accuracy = round(sum(cv_score) / len(cv_score)*100, 2)
        print(f'Cross validation accuracy for {model}: \n{cv_score}')
        print('==='*20)

models_comparison_using_cross_validation()

Cross validation accuracy for LogisticRegression(max_iter=1000): 
[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Cross validation accuracy for SVC(kernel='linear'): 
[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Cross validation accuracy for KNeighborsClassifier(): 
[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Cross validation accuracy for RandomForestClassifier(): 
[0.83606557 0.90163934 0.80327869 0.83333333 0.78333333]
